<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="PDFsharp-MigraDoc" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="ScottPlot" />
  </ItemGroup>
</Project>
